services:
  - type: web
    name: focussphere
    runtime: docker
    plan: starter
    region: ohio
    dockerfile: ./Dockerfile
    dockerContext: ./
    buildCommand: docker build
    startCommand: ""
    healthCheckPath: /h2-console
    port: 8080
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
      - key: PORT
        value: "8080"
    autoDeploy: true
